<?php
    require_once(dirname(dirname(__FILE__))."/engine/engine.php");

    use Facebook\FacebookRedirectLoginHelper;
    use Facebook\FacebookRequestException;
    use Facebook\FacebookRequest;
    use Facebook\GraphUser;
    
    global $TeKe;

    $helper = new FacebookRedirectLoginHelper(WWW_ROOT . 'actions/login.php');

    try {
        $session = $helper->getSessionFromRedirect();
    } catch(FacebookRequestException $ex)  {
        error_log($ex->getMessage());
    } catch(\Exception $ex) {
        error_log($ex->getMessage());
    }

    if ($session) {
        try {
            $me = (new FacebookRequest($session, 'GET', '/me'))->execute()->getGraphObject(GraphUser::className());

            $exists = $TeKe->user->check_facebook_id_exists($me->getId());
            if (!$exists) {
                // Username has been deprecated, using autogenerated instead
                $user_created = $TeKe->user->create('fb' . $me->getId(), $me->getProperty('email'), $me->getId(), $me->getFirstName(), $me->getLastName());
                if (!$user_created) {
                    $TeKe->add_system_message('Account could not be created. Please contact administrator.', 'error');
                    if (!$me->getProperty('email')) {
                        $TeKe->add_system_message('No email address found. Please make sure to have a validated email address on your account!', 'error');
                    }
                }
            }
            $user = $TeKe->user->get_user_by_facebook_id($me->getId());
            if ($user) {
                $user->updateLastLoginTime();
                unset($_SESSION['user']);
                $_SESSION['user'] = $user->id;
            } else {
                $TeKe->add_system_message(_("Login failed."), 'error');
            }
        } catch (FacebookRequestException $ex) {
            error_log($ex->getMessage());
            $TeKe->add_system_message(_("Facebook profile could not be loaded."), 'error');
        } catch (\Exception $ex) {
            error_log($ex->getMessage());
            $TeKe->add_system_message(_("Facebook profile could not be loaded."), 'error');
        }
    } else {
        $TeKe->add_system_message(_("Facebook login failed."), 'error');
    }

    forward(WWW_ROOT);
