<?php
    require_once(dirname(dirname(__FILE__))."/engine/engine.php");

    global $TeKe;

    $fb = $TeKe->getFacebookService();
    $helper = $fb->getRedirectLoginHelper();

    try {
        $accessToken = $helper->getAccessToken();
    } catch(Facebook\Exceptions\FacebookResponseException $e) {
        error_log('Graph returned an error: ' . $e->getMessage());
    } catch(Facebook\Exceptions\FacebookSDKException $e) {
        error_log('Facebook SDK returned an error: ' . $e->getMessage());
    }

    if (isset($accessToken) && $accessToken) {
        try {
            $response = $fb->get('/me?fields=id,email,first_name,last_name', $accessToken);
            $user = $response->getGraphUser();
            $exists = $TeKe->user->check_facebook_id_exists($user->getId());

            if (!$exists) {
                // Username has been deprecated, using autogenerated instead
                $user_created = $TeKe->user->create('fb.' . $user->getId(), $user->getField('email'), $user->getId(), $user->getFirstName(), $user->getLastName());
                if (!$user_created) {
                    $TeKe->add_system_message('Account could not be created. Please contact administrator.', 'error');
                    if (!$user->getField('email')) {
                        $TeKe->add_system_message('No email address found. Please make sure to have a validated email address on your account!', 'error');
                    }
                }
            }
            $user = $TeKe->user->get_user_by_facebook_id($user->getId());
            if ($user) {
                $user->updateLastLoginTime();
                unset($_SESSION['user']);
                $_SESSION['user'] = $user->id;
            } else {
                $TeKe->add_system_message(_("Login failed."), 'error');
            }

        } catch(Facebook\Exceptions\FacebookResponseException $e) {
            error_log('Graph returned an error: ' . $e->getMessage());
            $TeKe->add_system_message(_("Facebook profile could not be loaded."), 'error');
        } catch(Facebook\Exceptions\FacebookSDKException $e) {
            error_log('Facebook SDK returned an error: ' . $e->getMessage());
            $TeKe->add_system_message(_("Facebook profile could not be loaded."), 'error');
        }
    } else {
        $TeKe->add_system_message(_("Facebook login failed."), 'error');
    }

    forward(WWW_ROOT);
